# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\firstUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from urllib.request import urlretrieve

class Ui_MainWindow(object):
   #my functions 


    def handle_Progress(self, blocknum, blocksize,totalsize):
        read = blocknum * blocksize
        if totalsize > 0 :
            download_percetage = read *100 / totalsize
            self.progressBar.setValue(download_percetage)
            QtWidgets.QApplication.processEvents()


        #run Comand
    def run_comand(self):
        self.downloadUrl = self.lineEdit.text()
        self.fileLocation = self.lineEdit_2.text()
        if self.fileLocation and self.downloadUrl :
            try:
                urlretrieve(self.downloadUrl, self.fileLocation, self.handle_Progress)
            except OSError:
                self.label.setText('Write your file name')
        else:
            print('fill the line edits')
    #open file explorer
    def openDialog(self):
        dir_ = QtWidgets.QFileDialog.getSaveFileName(None, caption='Select',directory=".")
        self.lineEdit_2.setText(dir_[0])
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(679, 406)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 681, 401))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(280, 310, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(120, 60, 411, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 100, 371, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 100, 21, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setGeometry(QtCore.QRect(120, 170, 421, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(56, 220, 551, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(10, 90, 91, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 679, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        #clicked events
        self.pushButton.clicked.connect(self.run_comand)
        self.pushButton_2.clicked.connect(self.openDialog)
        self.comboBox.currentTextChanged.connect(self.get_data)
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def get_data(self):
        if self.comboBox.currentText() =='Video':
            self.lineEdit_2.setText('C:/Users/ghaem/Video/')
        if self.comboBox.currentText() =='Document':
            self.lineEdit_2.setText('C:/Users/ghaem/Document/')
        if self.comboBox.currentText() =='Other':
            self.lineEdit_2.setText('C:/Users/ghaem/Downloads/')
        if self.comboBox.currentText()=='Picture':
            self.lineEdit_2.setText('C:/Users/ghaem/Picture/')
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Download"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter Link"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Enter Patch"))
        self.pushButton_2.setText(_translate("MainWindow", "B"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Document"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Video"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Other"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Picture"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
